dotnetapp/Madmox.Website.Web/ViewComponents/Footer/FooterViewComponent.cs
using Madmox.Website.Core.Git;
using Microsoft.AspNetCore.Mvc;

namespace Madmox.Website.Web.ViewComponents.Footer
{
    [ViewComponent(Name = "Footer")]
    public class FooterViewComponent : ViewComponent
    {
        private readonly IGitService _git;

        public FooterViewComponent(
            IGitService git
        )
        {
            this._git = git;
        }

        public IViewComponentResult Invoke()
        {
            string revisionHash = this._git.GetRevisionHash();

            var vm = new FooterViewModel()
            {
                RevisionHash = revisionHash
            };
            return this.View(vm);
        }
    }
}

dotnetapp/Madmox.Website.Web/ViewComponents/Navigation/NavigationViewComponent.cs
using Madmox.Website.Core.Types;
using Madmox.Website.DataAccess.Database.Entities;
using Madmox.Website.DataAccess.Database.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Madmox.Website.Web.ViewComponents.Navigation
{
    [ViewComponent(Name = "Navigation")]
    public class NavigationViewComponent : ViewComponent
    {
        private readonly IRecipeCategoryRepository _recipeCategoryRepository;

        public NavigationViewComponent(
            IRecipeCategoryRepository recipeCategoryRepository
        )
        {
            this._recipeCategoryRepository = recipeCategoryRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            string category = (string)this.ViewContext.ViewData[Constants.Navigation.CATEGORY];
            string subcategory = (string)this.ViewContext.ViewData[Constants.Navigation.SUBCATEGORY];
            var recipeCategories = new List<RecipeCategoryDTO>();
            if (category == "recipes")
            {
                EntitySet<RecipeCategoryEntity> dbRecipeCategories = await this._recipeCategoryRepository.List();
                foreach (RecipeCategoryEntity dbRecipeCategory in dbRecipeCategories)
                {
                    var entry = new RecipeCategoryDTO();
                    entry.Map(dbRecipeCategory);
                    recipeCategories.Add(entry);
                }
            }

            var vm = new NavigationResponseDTO()
            {
                Category = category,
                Subcategory = subcategory,
                RecipeCategories = recipeCategories
            };
            return this.View(vm);
        }
    }
}

dotnetapp/Madmox.Website.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html prefix="og: https://ogp.me/ns#">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width,initial-scale=1" />
	<title>@ViewData["Title"] - www.madmox.fr</title>
	<meta name="description" content="@ViewData["Description"]" />
	<meta name="robots" content="index,follow" />
	<link rel="icon" type="image/png" sizes="16x16" href="~/static/images/favicon_16.png" />
	<link rel="icon" type="image/png" sizes="32x32" href="~/static/images/favicon_32.png" />
	<link rel="stylesheet" href="~/static/css/site.css" />
	@RenderSection("HeadEnd", required: false)
</head>
<body>
	<header class="page-head">
		<nav>
			<nav-entry category="default" url="@Url.Page("/Index")">Accueil</nav-entry>
			<nav-entry category="recipes" url="@Url.Page("/Recipes/Index")">Recettes</nav-entry>
		</nav>
		<nav class="account">
			@if (User.Identity.IsAuthenticated)
			{
				<nav-entry category="account" subcategory="profile" url="@Url.Page("/Account/Profile")">Mon compte</nav-entry>
			}
			else if ((string)ViewContext.RouteData.Values["page"] == "/Account/SignIn")
			{
				<nav-entry category="account" subcategory="signin" url="@Url.Page("/Account/SignIn", new { ReturnUrl = Context.Request.Query["ReturnUrl"] })">Connexion</nav-entry>
			}
			else
			{
				<nav-entry category="account" subcategory="signin" url="@Url.Page("/Account/SignIn", new { ReturnUrl = $"{Context.Request.Path}{Context.Request.QueryString}" })">Connexion</nav-entry>
			}
		</nav>
	</header>
	<main class="page-content">
		@await Component.InvokeAsync("Navigation")
		<div class="page-view">
			@RenderBody()
		</div>
	</main>
	<footer class="page-footer">
		@await Component.InvokeAsync("Footer")
	</footer>
	@RenderSection("BodyEnd", required: false)
</body>
</html>